### ISSUE TITLE
Button BROWSE error

### ISSUE THREAD

**Issue by MyraBaba** [knetrix/Keyword-Extraction-From-Text#13]
when press BROWSE:

Traceback (most recent call last):
  File "/data/WORKS/keyword-extraction-project-from-text-with-textrank-and-rake-algorithm/file_selection_process.py", line 195, in file_select
    os.chdir(os.path.join(os.path.join(os.environ["USERPROFILE"]), "Desktop"))
  File "/home/alp2080/miniconda3/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'USERPROFILE'
Aborted (core dumped)

**Comment by knetrix** [comment]
I noticed that the project does not work in Python 3.10 version. When I try it with Python 3.9.6 version, there seems to be no problem. Also, since the project name was long, it gave an error at the beginning, and I fixed that too. I Updated the Project Description for This.
